# Cloud Build configuration for MotorScope API
# Builds Docker image and deploys to Cloud Run
#
# INFRASTRUCTURE NOTE:
# This deployment uses infrastructure managed by Terraform (see /terraform).
# The following resources must exist before running this build:
# - Artifact Registry repository (motorscope)
# - Cloud Run service (motorscope-api)
# - Secret Manager secrets (jwt-secret, oauth-client-id, allowed-origin-extension)
#
# SECURITY: Configure trigger with Repository Event Filter (CEL):
#   push.pusher.name == "pbuchman"
# This filters at trigger level using authenticated GitHub webhook data

steps:
  # Log build info
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=============================================="
        echo "MotorScope API Deployment"
        echo "=============================================="
        echo "Environment: ${_ENVIRONMENT}"
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $SHORT_SHA"
        echo "Trigger: $TRIGGER_NAME"
        echo "Project: $PROJECT_ID"
        echo "Region: ${_REGION}"
        echo "Service: ${_SERVICE_NAME}"
        echo "Pusher: ${_PUSHER_NAME}"
        echo "=============================================="

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'api'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=${_BUCKET_NAME}'
      - '--set-secrets'
      - 'JWT_SECRET=jwt-secret:latest,OAUTH_CLIENT_ID=oauth-client-id:latest,ALLOWED_ORIGIN_EXTENSION=allowed-origin-extension:latest'

# Substitution variables (can be overridden in trigger)
# Default values are for the development environment
substitutions:
  _PUSHER_NAME: '$(body.pusher.name)'
  _ENVIRONMENT: 'development'
  _REGION: 'europe-west1'
  _REPOSITORY: 'motorscope'
  _SERVICE_NAME: 'motorscope-api'
  _BUCKET_NAME: 'motorscope-images'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

